### PR TITLE
Odpi

### LINKED ISSUE #23: Recources across nodes
Resources are being cleaned up when the corresponding Erlang term is garbage collected. However, this does not work across nodes because of reference counting: the refcount reaches 0 for the slave node and it deallocates the resource. A mechanism is required that corrects the issue of resources being freed too early. It should also be able to free them as soon as they are not required anymore, not just when the whole context dies (for instance millions of statements being made and destroyed back to back) and perhaps it could also handle resources left behind in the wake of unexpected termination.

### PR DESCRIPTION
**Pull request by KarlKeiser**
fixes #23
Support for [ODPI-C](https://oracle.github.io/odpi/doc/)

### CODE REVIEW

File: c_src/dpiContext_nif.c [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		dpiContext_destroy(dpiContext->context);
+		dpiContext->context = NULL;
+		L("dpiContext destroyed\r\n");
+	}
+}
+
+DPI_NIF_FUN(dpiContext_create)
+{
+	int major = 1;
+	int minor = 0;
```
Comment (c-bik) [inline c_src/dpiContext_nif.c]: Do not initialize.
`int major, minor`

File: c_src/dpiContext_nif.c [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+	ERL_NIF_TERM map = enif_make_new_map(env);
+	enif_make_map_put(env, map, enif_make_atom(env, "context"), nif_res, &map);
+	return map;
+}
+
+DPI_NIF_FUN(dpiContext_getError)
+{
+	int major = 1;
+	int minor = 0;
+	dpiErrorInfo error;
```
Comment (c-bik) [inline c_src/dpiContext_nif.c]: major, minor unused variables, delete them

File: c_src/dpi_nif.h [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+#define _DPI_NIF_H_
+#include "erl_nif.h"
+
+#include "stdio.h"
+
+#define TRACE printf("[%s:%s:%d]\r\n", __FILE__, __FUNCTION__, __LINE__)
+#undef TRACE
+#define TRACE
+#define CALL_TRACE \
+	printf("[%s:%s:%d] called\r\n", __FILE__, __FUNCTION__, __LINE__)
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Add `fflush(stdout)`

File: c_src/dpi_nif.h [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+#define RETURNED_TRACE \
+	printf("[%s:%s:%d] returned\r\n", __FILE__, __FUNCTION__, __LINE__)
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Add `fflush(stdout)`

File: c_src/dpi_nif.h [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+	ERL_NIF_TERM _fun##_nif( \
+		ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[])
+
+#define UNIMPL(x)                         \
+	DPI_NIF_FUN(x)                        \
+	{                                     \
+		return TUPLE_ERROR_UNIMPLIMENTED; \
+	}
+
+#define DPI_CHECK_ERROR(__ctx, __error, __exprn)           \
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Remove one `_` from argument. Single `_` prefix is enough

File: c_src/dpi_nif.h [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+	{                                                                \
+#_fun "_nif", _arity, _fun##_nif, ERL_NIF_DIRTY_JOB_IO_BOUND \
+	}
+
+#define DPI_NIF_FUN(_fun)    \
+	ERL_NIF_TERM _fun##_nif( \
+		ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[])
+
+#define UNIMPL(x)                         \
+	DPI_NIF_FUN(x)                        \
```
Comment (c-bik) [inline c_src/dpi_nif.h]: rename `x` -> `_fun`

File: priv/README [hunk 7]
```diff
@@ -0,0 +1 @@
+too lazy to detect and create empty priv folder from makefile ;)
```
Comment (c-bik) [inline priv/README]: May be now is a good time to do that 😉

File: c_src/dpi_nif.c [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+* dpiContext_*
+* dpiConn_*
+* dpiStmt_*
+*/
+#ifdef EMBED
+#include "odpi/embed/dpi.c"
+#endif
+
+#include "dpi_nif.h"
+#include "stdio.h"
```
Comment (c-bik) [inline c_src/dpi_nif.c]: `dpi_nif.h` already includes `stdio.h`

File: c_src/dpi_nif.h [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+	{                                     \
+		return TUPLE_ERROR_UNIMPLIMENTED; \
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Instead `return enif_make_tuple2(env, ATOM_ERROR, ATOM_UNIMPLIMENTED):`

File: c_src/dpi_nif.c [hunk 10]
```diff
@@ -0,0 +1,85 @@
...
+#include "dpiConn_nif.h"
+#include "dpiStmt_nif.h"
+#include "dpiQueryInfo_nif.h"
+
+ERL_NIF_TERM ATOM_OK;
+ERL_NIF_TERM ATOM_NULL;
+ERL_NIF_TERM ATOM_ERROR;
+ERL_NIF_TERM ATOM_ENOMEM;
+ERL_NIF_TERM ATOM_UNIMPLIMENTED;
+ERL_NIF_TERM TUPLE_ERROR_UNIMPLIMENTED;
```
Comment (c-bik) [inline c_src/dpi_nif.c]: `TUPLE_ERROR_UNIMPLIMENTED` not needed as, `{error, unimplimented}` term is created at return in `UNIMPLIMENTED`  macro

File: c_src/dpi_nif.h [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+#define IOB_NIF(_fun, _arity)                                        \
+	{                                                                \
+#_fun "_nif", _arity, _fun##_nif, ERL_NIF_DIRTY_JOB_IO_BOUND \
+	}
+
+#define DPI_NIF_FUN(_fun)    \
+	ERL_NIF_TERM _fun##_nif( \
+		ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[])
+
+#define UNIMPL(x)                         \
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Rename `UNIMPL` -> `UNIMPLIMENTED`

File: c_src/dpiStmt_nif.c [hunk 12]
```diff
@@ -0,0 +1,507 @@
...
+		//dat.value.asTimestamp.tzMinuteOffset = tzMinuteOffset;
+
+		if (!enif_get_map_value(
+				env, dataTerm, enif_make_atom(env, "tzHourOffset"), &mapValue))
+			return RAISE_EXCEPTION("Bad data argument");
+		int tzHourOffset;
+		enif_get_int(env, mapValue, &tzHourOffset);
+		//dat.value.asTimestamp.tzHourOffset = tzHourOffset;
+		dpiData_setTimestamp(dat, year, month, day, hour, minute, second,
+							 fsecond, tzHourOffset, tzMinuteOffset);
```
Comment (c-bik) [inline c_src/dpiStmt_nif.c]: **IMPORTANT** _there shouldn't be any `dpi*` function calls other than `dpiStmt` in `dpiStmt_nif.c`_

File: c_src/dpi_nif.h [hunk 13]
```diff
@@ -0,0 +1,83 @@
...
+
+#include "stdio.h"
+
+#define TRACE printf("[%s:%s:%d]\r\n", __FILE__, __FUNCTION__, __LINE__);\
+ fflush(stdout)
+#undef TRACE
+#define TRACE
+#define CALL_TRACE \
+	printf("[%s:%s:%d] called\r\n", __FILE__, __FUNCTION__, __LINE__);\
+    fflush(stdout)
```
Comment (c-bik) [inline c_src/dpi_nif.h]: not autoformatting?

File: c_src/dpi_nif.h [hunk 14]
```diff
@@ -0,0 +1,83 @@
...
+
+#ifndef __WIN32__
+#define L(_Format, ...)                                                            \
+	printf("[%s:%s:%d] "_Format, __FILE__, __FUNCTION__, __LINE__, ##__VA_ARGS__); \
+	fflush(stdout)
+
+#define E(_str, ...)                  \
+	L("ERROR: " _str, ##__VA_ARGS__); \
+	fflush(stdout)
```
Comment (c-bik) [inline c_src/dpi_nif.h]: Macro `L` already has `fflush(stdout)`

File: priv/README (hunk 7 above)
Comment (c-bik) [reply priv/README]: Please let me if we cann't create missing folders from Windows Makefiles and why?

Comment (c-bik) [reply priv/README]: mkdir in Makefile -- solved

File: src/dpi.erl [hunk 15]
```diff
@@ -151,6 +142,18 @@ refList(Input) when is_list(Input)->
     );
 refList(_Input) -> [].
 
+rpc_load_map(Slave) ->
```
Comment (c-bik) [inline src/dpi.erl]: Rename `gen_server_rpc_start`

File: src/dpi.erl [hunk 16]
```diff
@@ -151,6 +142,18 @@ refList(Input) when is_list(Input)->
...
+    Res = rpc_call(
+        Slave, gen_server, start_link,
+        [{local, ?MODULE}, ?MODULE, [], []]
+        ),
```
Comment (c-bik) [inline src/dpi.erl]: Indent as follows:
```erlang
Res = rpc_call(
    Slave, gen_server, start_link,
    [{local, ?MODULE}, ?MODULE, [], []]
),
```

File: c_src/dpiData_nif.h [hunk 17]
```diff
@@ -0,0 +1,120 @@
...
+        M2A(DPI_NATIVE_TYPE_OBJECT, _assign);                        \
+        M2A(DPI_NATIVE_TYPE_STMT, _assign);                          \
+        M2A(DPI_NATIVE_TYPE_BOOLEAN, _assign);                       \
+        M2A(DPI_NATIVE_TYPE_ROWID, _assign);                         \
+    default:                                                         \
+        return RAISE_EXCEPTION("dpiNativeType value not supported"); \
+    }
+
+
+
```
Comment (c-bik) [inline c_src/dpiData_nif.h]: remove extra new lines

File: src/dpi.erl [hunk 18]
```diff
@@ -0,0 +1,161 @@
...
+refList(Input) when is_map(Input)-> refList(maps:values(Input));
+refList(Input) when is_reference(Input)-> [Input];
+refList(Input) when is_list(Input)->
+    lists:filter(
+        fun is_reference/1,
+        lists:flatten([refList(X) || X <- Input])
+    );
+refList(_Input) -> [].
+
+rpc_load_map(Slave) ->
```
Comment (c-bik) [inline src/dpi.erl]: Rename `gen_server_rpc_start`

File: src/dpi.erl [hunk 19]
```diff
@@ -0,0 +1,161 @@
...
+    Res = rpc_call(
+        Slave, gen_server, start_link,
+        [{local, ?MODULE}, ?MODULE, [], []]
+        ),
```
Comment (c-bik) [inline src/dpi.erl]: Indent as follows:
```erlang
Res = rpc_call(
    Slave, gen_server, start_link,
    [{local, ?MODULE}, ?MODULE, [], []]
),
```

File: test/connect.config [hunk 20]
```diff
@@ -0,0 +1,12 @@
+%%-*- mode: erlang -*-
+%% ex: ft=erlang
+
+#{
+tns => <<"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS="
+         "(PROTOCOL=tcp)(HOST=192.168.1.43)(PORT=1521)))"
+         "(CONNECT_DATA=(SERVICE_NAME=XE)))">>,
+user => <<"scott">>,
+password => <<"regit">>,
```
Comment (c-bik) [inline test/connect.config]: Remove real IP/Port/Passwords

File: c_src/dpiConn_nif.c [hunk 21]
```diff
@@ -0,0 +1,340 @@
...
+
+	ERL_NIF_TERM stmtResTerm = enif_make_resource(env, stmtRes);
+	enif_release_resource(stmtRes);
+
+	return stmtResTerm;
+}
+
+DPI_NIF_FUN(dpiConn_newVar)
+{
+	CHECK_ARGCOUNT(8);
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: fix indentation of the entire function

File: c_src/dpiConn_nif.c [hunk 22]
```diff
@@ -0,0 +1,340 @@
...
+    enif_make_map_put(env, ret, enif_make_atom(env, "var"), varResTerm, &ret);
+	enif_make_map_put(env, ret, enif_make_atom(env, "data"), dataList, &ret);
+		
+	return ret;
+}
+
+DPI_NIF_FUN(dpiConn_commit)
+{
+	CHECK_ARGCOUNT(1);
+
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: remove newline

File: c_src/dpiConn_nif.c [hunk 23]
```diff
@@ -0,0 +1,340 @@
...
+void dpiConn_res_dtor(ErlNifEnv *env, void *resource)
+{
+	TRACE;
+	L("dpiConn destroyed\r\n");
+}
+
+DPI_NIF_FUN(dpiConn_create)
+{
+	CHECK_ARGCOUNT(6);
+
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: remove newline

File: c_src/dpiConn_nif.c [hunk 24]
```diff
@@ -0,0 +1,340 @@
...
+			connRes->conn, mode,
+			tag.size > 0 ? tag.data : NULL,
+			tag.size));
+
+	return ATOM_OK;
+}
+
+DPI_NIF_FUN(dpiConn_getServerVersion)
+{
+	CHECK_ARGCOUNT(1);
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: fix indent

File: c_src/dpiConn_nif.c [hunk 25]
```diff
@@ -0,0 +1,340 @@
...
+        enif_make_string_len(env, releaseString, releaseStringLength, ERL_NIF_LATIN1), &map);
+    // return #{ versionNum => integer, releaseNum => integer,
+    // updateNum => integer, portReleaseNum => integer, 
+    // portUpdateNum => integer, fullVersionNum => integer }
+    return map;
+}
+
+DPI_NIF_FUN(dpiConn_getObjectType)
+{
+	CHECK_ARGCOUNT(2);
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: cleanup and fix indent

File: c_src/dpiStmt_nif.c [hunk 26]
```diff
@@ -0,0 +1,313 @@
...
+    if (!enif_get_resource(env, argv[2], dpiVar_type, &varRes))
+        return BADARG_EXCEPTION(2, "resource var");
+
+    RAISE_EXCEPTION_ON_DPI_ERROR(
+        dpiStmt_define(stmtRes->stmt, pos, varRes->var));
+
+    return ATOM_OK;
+}
+
+DPI_NIF_FUN(dpiStmt_defineValue){
```
Comment (c-bik) [inline c_src/dpiStmt_nif.c]: Function body start `{` on a new line

File: c_src/dpiConn_nif.c (hunk 21 above)
Comment (c-bik) [reply c_src/dpiConn_nif.c]: Please use 4 spaces in stead of Tab for indentation

File: c_src/dpiConn_nif.c [hunk 27]
```diff
@@ -0,0 +1,339 @@
...
+	ErlNifBinary name;
+
+	if (!enif_get_resource(env, argv[0], dpiConn_type, &connRes))
+		return BADARG_EXCEPTION(0, "resource connection");
+	if (!enif_inspect_binary(env, argv[1], &name))
+		return BADARG_EXCEPTION(2, "binary/string name");
+
+	dpiObjectType_res *objectTypeRes =
+		enif_alloc_resource(dpiObjectType_type, sizeof(dpiObjectType_res));
+	objectTypeRes->objectType = NULL; // remove if unneeded
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: needed / not-needed?

File: c_src/dpiConn_nif.c [hunk 28]
```diff
@@ -0,0 +1,339 @@
...
+    dpiConn_res *connRes = NULL;
+
+    if (!enif_get_resource(env, argv[0], dpiConn_type, &connRes))
+        return BADARG_EXCEPTION(0, "resource connection");
+
+    dpiVersionInfo version;
+	char *releaseString;
+	int releaseStringLength;
+    dpiConn_getServerVersion(connRes->conn, &releaseString,
+							 &releaseStringLength, &version);
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: Fix indent!

File: c_src/dpiConn_nif.c [hunk 29]
```diff
@@ -0,0 +1,339 @@
...
+        enif_make_int(env, version.portUpdateNum), &map);
+
+    enif_make_map_put(
+        env, map, enif_make_atom(env, "fullVersionNum"),
+        enif_make_int(env, version.fullVersionNum), &map);
+
+	enif_make_map_put(
+        env, map, enif_make_atom(env, "releaseString"),
+        enif_make_string_len(env, releaseString, releaseStringLength,
+							 ERL_NIF_LATIN1), &map);
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: fix indent
