### PR TITLE
fix list handling in stmt_execute and conn_close

### LINKED ISSUE #89: enif_get_list_cell is not called
https://github.com/K2InformaticsGmbH/oranif/blob/8a555c02e94cd1fad1eeecf7e7f0e06bceea8c37/c_src/dpiConn_nif.c#L311-L313
https://github.com/K2InformaticsGmbH/oranif/blob/8a555c02e94cd1fad1eeecf7e7f0e06bceea8c37/c_src/dpiStmt_nif.c#L28-L30

If `argv[1]` is a list `enif_is_list(env, argv[1])` will be **true** and `!enif_is_list(env, argv[1])` will be **false** which reduces the expression effectively to:
`if(false && !enif_get_list_cell(env, argv[1], &head, &tail))`

According to https://en.cppreference.com/w/c/language/eval_order
> 2) There is a sequence point after evaluation of the first (left) operand and before evaluation of the second (right) operand of the following binary operators: && (logical AND), || (logical OR), and , (comma).

`enif_get_list_cell(env, argv[1], &head, &tail)` this is never evaluated hence `head` and `tail` were never assigned!

### PR DESCRIPTION
**Pull request by KarlKeiser**
fixes #89

### CODE REVIEW

File: c_src/dpiConn_nif.c [hunk 1]
```diff
@@ -287,9 +287,9 @@ DPI_NIF_FUN(conn_close)
 
     if (!enif_get_resource(env, argv[0], dpiConn_type, (void **)&connRes))
         BADARG_EXCEPTION(0, "resource connection");
-
-    if (!enif_is_list(env, argv[1]) &&
-        !enif_get_list_cell(env, argv[1], &head, &tail))
+    if (enif_is_list(env, argv[1]))
+        enif_get_list_cell(env, argv[1], &head, &tail);
+    else
```
Comment (c-bik) [inline c_src/dpiConn_nif.c]: As per the conditions:
image
and from
image

Please check if the rewrite works
```c
unsigned len;
if (!enif_get_list_length(env, argv[1], &len))
    BADARG_EXCEPTION(1, "atom list modes, not a list");
if (len > 0 && !enif_get_list_cell(env, argv[1], &head, &tail))
    BADARG_EXCEPTION(1, "atom list modes");
```

Comment (KarlKeiser) [reply c_src/dpiConn_nif.c]: yes, that also works
